version: '3'
services:
  web:
    build: .
    # volumes:
    #  - ./build/libs:/build/libs
    #  - ./shared/logs:/opt/jboss/standalone/log
    ports:
     - "8080:8080"
     - "9990:9990"
  redis:
    image: "redis:alpine"
