version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    volumes:
      - ./redmine_data:/usr/src/redmine/files
    ports:
      - 58080:3000
    environment:
      REDMINE_DB_POSTGRES: db
      REDMINE_DB_USERNAME: postgres
      REDMINE_DB_PASSWORD: password
#  db:
#    image: mysql:5.7
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: example
#      MYSQL_DATABASE: redmine

  db:
    restart: always
    image: postgres:9.6.8
    ports:
      - 25432:5432
#    volumes:
#      - ./redmine_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres


#  POSTGRES_DB: pgdb
